# Generated by Django 4.2.30 on 2026-09-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardia_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompromisoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('tipo_turno', models.CharField(choices=[('Diurna', 'Diurna'), ('Nocturna', 'Nocturna')], default='Diurna', max_length=20, verbose_name='Turno Seleccionado')),
                ('tipo_dia', models.CharField(choices=[('Semana', 'Día de Semana'), ('Fin de Semana', 'Fin de Semana')], default='Semana', max_length=20, verbose_name='Tipo de Día Seleccionado')),
                ('es_estudiante', models.BooleanField(default=False, verbose_name='¿Es Guardia Estudiantil?')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Firma')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='guardia_admin.perfil', verbose_name='Perfil del Titular')),
            ],
            options={
                'verbose_name': 'Compromiso de Guardia',
                'verbose_name_plural': 'Compromisos de Guardia',
                'ordering': ['-fecha_firma'],
            },
        ),
    ]
