# Generated by Django 4.2.30 on 2026-09-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardia_admin', '0001_initial'),
        ('potencial', '0001_initial'),
        ('compromiso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisoguardia',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromisos', to='potencial.periodoguardia', verbose_name='Período de Guardia'),
        ),
        migrations.AddField(
            model_name='compromisoguardia',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='guardia_admin.sede', verbose_name='Sede Seleccionada'),
        ),
        migrations.AlterUniqueTogether(
            name='compromisoguardia',
            unique_together={('perfil', 'periodo')},
        ),
    ]
