# Generated by Django 4.2.30 on 2026-09-04 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guardia_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoGuardia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Período')),
                ('inicio_compromiso', models.DateField(verbose_name='Inicio de Compromiso')),
                ('fin_compromiso', models.DateField(verbose_name='Fin de Compromiso')),
                ('inicio_aprobacion', models.DateField(verbose_name='Inicio de Aprobación')),
                ('fin_aprobacion', models.DateField(verbose_name='Fin de Aprobación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Período de Guardia',
                'verbose_name_plural': 'Períodos de Guardia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionPotencialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('aprobado', models.BooleanField(default=False, verbose_name='¿Potencial Aprobado?')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potenciales_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_potencial', to='guardia_admin.area')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_area', to='potencial.periodoguardia')),
            ],
            options={
                'verbose_name': 'Aprobación de Potencial por Área',
                'verbose_name_plural': 'Aprobaciones de Potencial por Área',
                'unique_together': {('periodo', 'area')},
            },
        ),
    ]
